### ISSUE TITLE
Add a Function to Calculate Factorial of a Number

### ISSUE THREAD

**Issue by Jadu07** [Jadu07/CodeFlex#1]
Issue Title: Implement a function to calculate the factorial of a number

Description: Create a Python function that takes an integer n as input and returns its factorial. Factorial of a number n is the product of all positive integers from 1 to n. For example, the factorial of 5 is 5 * 4 * 3 * 2 * 1 = 120.

You have to add code in Python Folder

**Comment by rkt-1597** [comment]
@Jadu07 Can this issue be assigned to me?

**Comment by Necro-Rohan** [comment]
@Jadu07 assign me this issue please
