### ISSUE TITLE
Print a Butterfly Pattern Using Stars.

### ISSUE THREAD

**Issue by Jadu07** [Jadu07/CodeFlex#30]
Write a program that takes an integer n as input and prints a butterfly pattern.

   Input
   First line will contain an integer n.
   Output
   Print the butterfly pattern with height and width 2n-1. (Print them without space in-between)

**Comment by adripo** [comment]
Hi @Jadu07 
I can work on this.

**Comment by Jadu07** [comment]
@adripo  assigned

**Comment by adripo** [comment]
@Jadu07 please have a look and let me know #33
