### ISSUE TITLE
Python Program to Print the Fibonacci sequence

### ISSUE THREAD

**Issue by singhal-amit** [Jadu07/CodeFlex#34]
Hi @Jadu07, I would like to contribute this problem. Can you assign this issue to me with the label `hacktoberfest` `hacktoberfest-accepted`

**Comment by ghulamhussainkhuhro** [comment]
Hi @Jadu07  I would like to contribute this problem. Can you assign this issue to me with the label hacktoberfest hacktoberfest-accepted
