### ISSUE TITLE
Implement a Function to Check Even or Odd

### ISSUE THREAD

**Issue by Jadu07** [Jadu07/CodeFlex#7]
Issue Title: Create a function to check if a number is even or odd

Description: Write a Python function that takes an integer as input and returns whether the number is even or odd.

You have to code in Python Folder

**Comment by Necro-Rohan** [comment]
@Jadu07  can you leave this issue to me

**Comment by mahirabidi12** [comment]
Please assign me this issue . I would like to contribute .
